name: echo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.* 
  - pip:
      - async-timeout==5.0.1
      - datasets==3.6.0
      - insightface==0.7.3
      - multiprocess==0.70.16
      - omegaconf==2.3.0
      - openai==1.88.0
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - transformers==4.51.0

