check_keys: ["prompt", "outputs", "prompt_fill_blank"]
system_prompt: "When you output the result, only emit strictly valid JSON.
- Use true/false for booleans.
- Do not include any trailing commas.
- Do not wrap the JSON in additional explanation."
prompt: |
  You are an extractor of multimodal prompts for image generation.

  Your task is to fill in the blanks of a partially given text prompt using the provided image.

  Please output only a valid JSON dictionary according to this schema:
  ```json {"prompt": <str>, "outputs": <list of ids>, "prompt_fill_blank": <bool>}```

  Instructions:
  - The prompt typically contains placeholders in brackets, e.g., "[SUBJECT]".
  - Your job is to infer and replace each placeholder with an appropriate keyword or phrase based on the provided image.
  - Only fill in the blank if you are fairly confident about what the placeholder should be. If you are uncertain, do not fill in the blank. Instead:
    - Set "prompt_fill_blank" to false.
    - Set "prompt" to an empty string.
    - Set "outputs" to an empty list.
  - If you successfully fill in the blank:
    - Set "prompt_fill_blank" to true.
    - Set "prompt" to the updated, filled-in prompt.
    - Set "outputs" to a list of the image filenames associated with this prompt.
  
  Input:
  prompt_to_update: <prompt>
  image: <images>
  
  Your Output (json only):
  